apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file docker-compose.yml --out ./k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "5172"
      port: 5172
      targetPort: 5172
  selector:
    io.kompose.service: api
