apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file docker-compose.yml --out ./k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cloud-custodian
  name: cloud-custodian
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloud-custodian
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file docker-compose.yml --out ./k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cloud-custodian
    spec:
      containers:
        - image: onderzoek-c7n-cloud-custodian:latest
          name: cloud-custodian
          volumeMounts:
            - mountPath: /usr/src/app/Policies
              name: cloud-custodian-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: cloud-custodian-cm0
          name: cloud-custodian-cm0
