apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file docker-compose.yml --out ./k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mail-service
  name: mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mail-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --file docker-compose.yml --out ./k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mail-service
    spec:
      containers:
        - image: c7n-onderzoek/mail-service:test
          name: mail-service
          imagePullPolicy: Never
      restartPolicy: Always
      
